apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
spec:
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: service2
        image: vaibhavsatam/envoy-service
        env:
        - name: SERVICE_NAME
          value: "2"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: envoy-service2
          containerPort: 5000
      - name: envoy-sidecar
        image: envoyproxy/envoy:v1.20-latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        args: ["-c", "/etc/envoy/envoy.yaml", "--service-cluster","service2","--service-node","service2"]
        ports:
        - name: envoy-sidecar
          containerPort: 8000
        volumeMounts:
        - name: envoy-service2-config
          mountPath: /etc/envoy
      volumes:
        - name: envoy-service2-config
          configMap:
            name: service2-config
