apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  selector:
    app: service2
  ports:
  - name: envoy-service2-port
    port: 5000
    targetPort: envoy-service2
  - name: envoy-sidecar-port
    port: 8000
    targetPort: envoy-sidecar
