apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: vaibhavsatam/envoy-service
        env:
        - name: SERVICE_NAME
          value: "1"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: envoy-service1
          containerPort: 5000
      - name: envoy-sidecar
        image: envoyproxy/envoy:v1.20-latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        args: ["-c", "/etc/envoy/envoy.yaml", "--service-cluster","service1","--service-node","service1"]
        ports:
        - name: envoy-sidecar
          containerPort: 8000
        volumeMounts:
        - name: envoy-service1-config
          mountPath: /etc/envoy
      volumes:
        - name: envoy-service1-config
          configMap:
            name: service1-config
