kind: Service
apiVersion: v1
metadata:
  name: opa
  labels:
    app: opa
spec:
  clusterIP: None
  selector:
    app: opa
  ports:
    - name: http
      protocol: TCP
      port: 8181
      targetPort: 8181
    - name: opa
      protocol: TCP
      port: 9002
      targetPort: 9002