apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1
spec:
  selector:
    matchLabels:
      app: service-1
  template:
    metadata:
      labels:
        app: service-1
    spec:
      containers:
      - name: service-1
        image: vaibhavsatam/envoy-service1
        env:
        - name: SERVICE_NAME
          value: service-1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
      - name: envoy-sidecar
        image: envoyproxy/envoy:v1.20-latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        args: ["-c", "/etc/envoy/envoy.yaml", "--service-cluster","${SERVICE_NAME}","--service-node","${SERVICE_NAME}"]
        env:
        - name: SERVICE_NAME
          value: service-1
        ports:
        - name: envoy-sidecar
          containerPort: 8000
        volumeMounts:
        - name: envoy-service-config
          mountPath: /etc/envoy
      volumes:
        - name: envoy-service-config
          configMap:
            name: service-config
