apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - name: httpbin
        image: kennethreitz/httpbin:latest
        resources: {}
        ports:
        - name: envoy-httpbin
          containerPort: 80
      - name: envoy
        image: envoyproxy/envoy:v1.20-latest
        resources: {}
        args: ["-c", "/etc/envoy/envoy.yaml", "--service-cluster","envoy-httpbin","--service-node","envoy-httpbin"]
        ports:
        - name: envoy-sidecar
          containerPort: 8000
        volumeMounts:
        - name: envoy-httpbin-config
          mountPath: /etc/envoy
      volumes:
        - name: envoy-httpbin-config
          configMap:
            name: envoy-httpbin