apiVersion: v1
kind: Service
metadata:
  name: httpbin-svc
spec:
  clusterIP: None
  selector:
    app: httpbin
  ports:
  - name: httpbin-envoy
    port: 5678
    targetPort: 5678
  - name: envoy-sidecar
    port: 8786
    targetPort: 80
  - name: envoy-admin
    port: 8001
    targetPort: 8001