apiVersion: v1
kind: Service
metadata:
  name: httpbin-svc
spec:
  clusterIP: None
  selector:
    app: httpbin
  ports:
  - name: envoy-httpbin-port
    port: 80
    targetPort: envoy-httpbin
  - name: envoy-sidecar-port
    port: 8000
    targetPort: envoy-sidecar
  - name: opa
    protocol: TCP
    port: 9002
    targetPort: 9002